require File.expand_path(File.dirname(__FILE__) + '/test_helper.rb')

class DataAccessorsTest < Test::Unit::TestCase
  
  include Templette::DataAccessors
  
  def test_should_add_helper
    assert !defined?(footer_blurb)
    require 'helpers/dynamic_helper'
    add_helper('dynamic_helper')
    assert defined?(footer_blurb)
    assert_equal 'generated by helper method', footer_blurb
  end
  
end