template_name: application_helper
sections:
  title:
    text: Home
    image: /images/title.jpg
  main:
   content: file:./pages/index.html
  inline:
    title:
      image: /images/whatever.jpg
  image:
    banner: /images/banner.jpg
